name: PatchMate Dependency Check

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday
  push:
    paths:
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:  # Allows manual execution

permissions:
  id-token: write   # Required for OIDC authentication with AWS
  contents: read

jobs:
  patchmate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::573451623612:role/GitHubActions-PatchMate
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run PatchMate Scan
        run: npx ts-node src/patchmate.ts
        env:
          AWS_REGION: us-east-1
